[tool.black]
max-line-length = 99
skip-string-normalization = true
target-version = ['py33']
extend-exclude = '''
^/tests/fixtures
'''

[tool.isort]
profile = "black"
filter_files = true
line_length = 99
