name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: ["**"]

jobs:
  run-tests:
    strategy:
      fail-fast: true
      matrix:
        st-version: [3, 4]
        os: ["ubuntu-latest", "macOS-latest", "windows-latest"]
    runs-on: ${{ matrix.os }}
    name: "Sublime Text ${{ matrix.st-version }} ({{ matrix.os }})"
    steps:
      - uses: actions/checkout@v2
      - uses: SublimeText/UnitTesting/actions/setup@v1
        with:
          sublime-text-version: ${{ matrix.st-version }}
      - uses: SublimeText/UnitTesting/actions/run-tests@v1
        with:
          coverage: true
          codecov-upload: true
